spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/login
    username: postgres
    password: 1234
  jpa:
    properties:
      hibernate:
        show_sql: true
        # format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace
