spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/login
    username: postgres
    password: 1234
  jpa:
    properties:
      hibernate:
        show_sql: true

  # amazon AWS
#  mail:
#    host: email-smtp.us-east-1.amazonaws.com
#    username: ${{ secrets.USERNAME_AWS }}
#    password: ${{ secrets.PASSWORD_AWS }}
#    properties:
#      mail:
#        transport.protocol: smtp
#        smtp:
#          port: 25
#          auth: true
#          starttls.enable: true
#          starttls.required: true
#          ssl.trust: email-smtp.us-east-1.amazonaws.com

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${ secret.EMAIL }
    password: ${ secret.PASSWORD }
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

logging:
  level:
    org:
      hibernate:
        type: trace